version: "3"
services:
  node:
    build: ./services/node
    container_name: node
    image: docker.nitra.pl/nitra/short:1.0.2
    restart: always
    environment:
      - "APP_DB_PORT=13000"
      - "APP_PORT=12010"
  mongo:
    image: mvertes/alpine-mongo
    restart: always
    volumes:
      - "vol:/data/db"
    ports:
      - "13000:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "12011:8081"

volumes:
  vol:
